module.exports = {
  purge: {
    content: ['./publish/**/*.html'],
    options: {
      safelist: [
        'tab-active',
        'searchresult',
        'md:flex',
        'md:w-1/3',
        'md:w-2/3',
        'border-b',
        'hover:bg-red-100',
        'absolute',
        'right-0',
        'bottom-0',
        'm-2',
        'text-xs',
        'text-gray-500',
        'text-red-500',
        'hover:text-gray-400',
        'bg-gray-800',
        'hover:bg-gray-700',
        'px-1',
        'rounded',
        'focus:outline-none',
        'transition',
        'duration-100',
      ],
      blocklist: [],
      keyframes: true,
      fontFace: true,
    },
  },
  theme: {
    extend: {
      colors: {
        red: {
          100: '#FDF8F6',
          200: '#FAEAE5',
          300: '#F3C7BA',
          400: '#EBA48E',
          500: '#E38163',
          600: '#DC5E38',
          700: '#BF4722',
          800: '#682712',
          900: '#341309',
        },
      },
      fontFamily: {
        sans: [
          'Open Sans',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: ['Fira Code', 'Fira Mono', 'Menlo', 'Monoco', 'monospace'],
      },
      spacing: {
        half: '0.125rem',
        22: '5.5rem',
        '9/16': '56.25%',
      },
    },
  },
  variants: {},
  plugins: [],
}
